# Generated by Django 6.0.4 on 2026-05-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_media"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="description",
        ),
        migrations.RemoveField(
            model_name="media",
            name="thumbnail_url",
        ),
        migrations.RemoveField(
            model_name="media",
            name="updated_at",
        ),
    ]
