# Generated by Django 6.0.4 on 2026-05-14 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_wordbook"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordBookEpisodeRel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wordbook_relations",
                        to="api.episode",
                    ),
                ),
                (
                    "wordbook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episode_relations",
                        to="api.wordbook",
                    ),
                ),
            ],
            options={
                "unique_together": {("wordbook", "episode")},
            },
        ),
    ]
