# Generated by Django 6.0.4 on 2026-05-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_wordbookepisoderel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="user_id",
            new_name="user",
        ),
    ]
