# Generated by Django 6.0.4 on 2026-05-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_rename_user_id_media_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordcard",
            name="is_learned",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="wordcard",
            name="word_grade",
            field=models.CharField(default="L1", max_length=2),
        ),
    ]
